language: cpp


sudo: required
dist: precise
group: legacy

os:
  - linux

compiler:
  - gcc

git:
  depth: 30

cache: apt

addons:
  postgresql: "9.1"

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

after_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/after_script.sh
